<template>
  <header>
    <common-header></common-header>
  </header>
  <article class="master-content">
    <h4>当前位置:大师风采</h4>
     <ul class="master-list ">
        <li v-for="item in items.region">
          <h2>{{item.title}}玉石雕刻大师</h2>
          <ul>
            <li v-for="ite in item.children">
              <a href={{ite.href}}>
                <figure>
                  <img src={{ite.src}} alt="arcter" />
                  <h5>{{ite.name}}</h5>
                  <p>
                    {{ite.sex}}&nbsp;{{ite.age}}年出生&nbsp;{{ite.area}}人
                  </p>
                </figure>
              </a>
            </li>
          </ul>
        </li>
     </ul>
  </article>
  <footer>
      <common-footer></common-footer>
  </footer>
</template>
<script>
import commonHeader from "components/common/header";
import commonFooter from "components/common/footer";
export default{ 
  //数据层
  data(){
    return{
      // 静态页面，整体数据层
      items:{
        region:[
          {
            title:"河南",
            children:[
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
            ]
          },
          {
            title:"河南",
            children:[
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
            ]
          },
          {
            title:"河南",
            children:[
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
              {
                src:"../../assets/images/master/master-arcter.png",
                href:'http://localhost:3000/views/masterInf/informatin.html',
                name:'王俊毅',
                sex:'男',
                age:'1975',
                area:'桂林'
              },
            ]
          },
        ]
      }
    }
  },
  components: {
    'common-header':commonHeader,
    'common-footer':commonFooter
  },
	ready() {

  }
}
</script>
<style  rel="stylesheet/scss" lang="sass">
    @import "../../sass/config";
    @import "../../sass/master/presence-main";
</style>
